# Generated by Django 3.1.4 on 2020-12-15 15:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import setfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Region')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country of Origin')),
                ('locales', setfield.SetField(base_field=models.TextField(), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('brand', models.CharField(blank=True, max_length=155, verbose_name='Winery Brand')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Winery')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Wineries / Vineyards',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=120, verbose_name='Wine Name (Label not Winery)')),
                ('vintage', models.IntegerField(verbose_name='Vintage (Year)')),
                ('grape_blend', models.CharField(max_length=255, verbose_name='Grape (Blend)')),
                ('one_liner', models.TextField(blank=True, verbose_name='One Line Description')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('wtype', models.CharField(choices=[('red', 'Red'), ('white', 'White'), ('rose', 'Rosé'), ('sparkling white', 'Sparkling White'), ('sparkling rose', 'Sparkling Rosé'), ('fortified', 'Fortified'), ('dessert', 'Dessert')], default='red', max_length=60, verbose_name='Red/White/Rose')),
                ('style', models.CharField(choices=[('unspecified', 'Unspecified'), ('light and perfumed', 'Light and Perfumed'), ('savory and classic', 'Savory and Classic'), ('bold and structured', 'Bold and Structured'), ('rich and intense', 'Rich and Intense'), ('aromatic and floral', 'Aromatic and Floral'), ('green and flinty', 'Green and Flinty'), ('tropical and balanced', 'Tropical and Balanced'), ('buttery and complex', 'Buttery and Complex'), ('dry and nutty', 'Dry and Nutty'), ('chocolate and caramel', 'Chocolate and Caramel'), ('caramelized and sticky', 'Caramelized and Sticky'), ('rich and warming', 'Rich and Warming'), ('lush and balanced', 'Lush and Balanced'), ('crisp and dry', 'Crisp and Dry'), ('rich and fruity', 'Rich and Fruity'), ('fresh and youthful', 'Fresh and Youthful'), ('complex and traditional', 'Complex and Traditional'), ('berries and cream', 'Berries and Cream'), ('sweet and spritzy', 'Sweet and Spritzy')], default='unspecified', max_length=60, verbose_name='Style')),
                ('list_price', models.DecimalField(decimal_places=2, default=999.99, max_digits=6)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wines.region')),
                ('winery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wines.winery')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
