# Generated by Django 3.1.4 on 2020-12-15 16:01

from django.db import migrations, models
import setfield


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='locales',
            field=setfield.SetField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
