# Generated by Django 3.1.4 on 2020-12-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_auto_20201215_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='alcohol_content',
            field=models.DecimalField(blank=True, decimal_places=1, default=14.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='wine',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='parker_points',
            field=models.IntegerField(blank=True, default=90),
        ),
        migrations.AddField(
            model_name='wine',
            name='star_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=3.0, max_digits=2),
        ),
    ]
