# Generated by Django 3.1.4 on 2020-12-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0003_auto_20201215_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
