# Generated by Django 3.1.4 on 2020-12-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0004_auto_20201215_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
