# Generated by Django 3.1.4 on 2020-12-23 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0005_auto_20201220_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region', to='wines.region'),
        ),
    ]
