# Generated by Django 3.1.4 on 2020-12-22 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_street_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('primary_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('primary_town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('primary_county', models.CharField(blank=True, max_length=80, null=True)),
                ('primary_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
